properties([
    [$class: 'org.jenkinsci.plugins.office365connector.WebhookJobProperty',
     webhooks: [[
         name: 'Teams-O365',
         url: 'https://lpnu.webhook.office.com/webhookb2/a91151cd-dd3b-4dd9-b309-00238eab8f53@7631cd62-5187-4e15-8b8e-ef653e366e7a/JenkinsCI/c9ba9dad5b07488e8d6468300698608b/294e4ebb-5ec1-414e-8bf6-c622514c87e0/V2_bXmLLapfaZFy4Ots1OH_gqcOvPKi8Wtfn2UcMLT5001',
         startNotification: false,
         notifySuccess: true,
         notifyAborted: false,
         notifyNotBuilt: false,
         notifyUnstable: true,
         notifyFailure: true,
         notifyBackToNormal: true,
         notifyRepeatedFailure: false,
         timeout: 30000
     ]]
    ]
])

pipeline {
    agent any

    stages {

        stage('Start') {
            steps {
                echo 'Lab_2: started by GitHub'
            }
        }

        stage('Modify HTML') {
            steps {
                echo 'Modifying index.html...'
                sh '''echo "<p>Generated by Jenkins on build #$BUILD_NUMBER</p>" >> index.html'''
            }
        }

        stage('Image build') {
            steps {
                sh "docker build -t prikm:latest ."
                sh "docker tag prikm dentsybko/prikm:latest"
                sh "docker tag prikm dentsybko/prikm:$BUILD_NUMBER"
                sh "docker tag prikm dentsybko/prikm:v2.$BUILD_NUMBER"
            }
        }

        stage('Push to registry') {
            steps {
                withDockerRegistry([ credentialsId: "dockerhub_token", url: "" ]) {
                    sh "docker push dentsybko/prikm:latest"
                    sh "docker push dentsybko/prikm:$BUILD_NUMBER"
                    sh "docker push dentsybko/prikm:v2.$BUILD_NUMBER"
                }
            }
        }

        stage('Clean Port 80') {
            steps {
                script {
                    def containerId = sh(script: "docker ps -q --filter 'publish=80'", returnStdout: true).trim()
                    if (containerId) {
                        sh "docker stop ${containerId}"
                        sh "docker rm ${containerId}"
                        echo "Stopped and removed container using port 80"
                    } else {
                        echo "Port 80 is free"
                    }
                }
            }
        }

        stage('Deploy image') {
            steps {
                sh "docker run -d -p 80:80 dentsybko/prikm"
            }
        }

        stage('Build') {
            steps {
                echo '🔧 Building project...'
            }
        }

        stage('Test') {
            steps {
                echo '🧪 Running tests...'
            }
        }

        stage('Deploy') {
            steps {
                echo '🚀 Deploying...'
            }
        }
    }

    post {
        success {
            echo '✅ Build finished successfully!'
        }
        failure {
            echo '❌ Build failed.'
        }
    }
}
