pipeline {
    agent any

    stages {

        stage('Start') {
            steps {
                echo 'Lab_2: started by GitHub'
            }
        }

        stage('Modify HTML') {
            steps {
                echo 'Modifying index.html...'
                sh '''echo "<p>Generated by Jenkins on build #$BUILD_NUMBER</p>" >> index.html'''
            }
        }

        stage('Image build') {
            steps {
                sh "docker build -t prikm:latest ."
                sh "docker tag prikm dentsybko/prikm:latest"
                sh "docker tag prikm dentsybko/prikm:$BUILD_NUMBER"
                sh "docker tag prikm dentsybko/prikm:v2.$BUILD_NUMBER"
            }
        }

        stage('Push to registry') {
            steps {
                withDockerRegistry([ credentialsId: "dockerhub_token", url: "" ]) {
                    sh "docker push dentsybko/prikm:latest"
                    sh "docker push dentsybko/prikm:$BUILD_NUMBER"
                    sh "docker push dentsybko/prikm:v2.$BUILD_NUMBER"
                }
            }
        }

        stage('Clean Port 80') {
            steps {
                script {
                    def containerId = sh(script: "docker ps -q --filter 'publish=80'", returnStdout: true).trim()
                    if (containerId) {
                        sh "docker stop ${containerId}"
                        sh "docker rm ${containerId}"
                        echo "Stopped and removed container using port 80"
                    } else {
                        echo "Port 80 is free"
                    }
                }
            }
        }

        stage('Deploy image') {
            steps {
                sh "docker run -d -p 80:80 dentsybko/prikm"
            }
        }

    }
}
